# Generated by Django 6.1.1 on 2026-09-04 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_recurringtransaction"),
        ("debts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="category",
            field=models.OneToOneField(
                blank=True,
                help_text="Automatisch angelegter Umschlag, über den Buchungen mit dieser Schuld verknüpft werden.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="debt",
                to="core.category",
            ),
        ),
        migrations.DeleteModel(
            name="DebtPayment",
        ),
    ]
