# Generated by Django 6.1.1 on 2026-09-05 09:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_category_icon"),
        ("debts", "0003_backfill_debt_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="account",
            field=models.OneToOneField(
                blank=True,
                help_text="Optional bei einer laufenden Kreditlinie (z.B. Kreditkarte): das Konto, dessen Buchungen automatisch die Restschuld verändern — normale Ausgaben erhöhen sie, Zahlungen (z.B. per Transfer) senken sie. Ohne Verknüpfung bleibt die klassische manuelle Zahlung über den Umschlag der Weg, die Restschuld zu ändern.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="debt",
                to="core.account",
            ),
        ),
        migrations.AddField(
            model_name="debt",
            name="last_interest_month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AddField(
            model_name="debt",
            name="last_interest_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
