# Generated by Django 6.1.1 on 2026-09-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debts", "0004_debt_account_link_and_interest_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="max_extra_payment",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximale zusätzliche Zahlung pro Monat über die Mindestrate hinaus, die dieser Kredit erlaubt — leer = unbegrenzt (z.B. Kreditkarte), 0 = keine Zuzahlung möglich (z.B. ein Ratenkredit mit fixem Tilgungsplan ohne freie Sondertilgung). Begrenzt, wie viel Extra-Budget der Tilgungsplan-Rechner auf diese Schuld verteilen darf.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
