# Generated by Django 6.1.1 on 2026-09-05 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debts", "0005_debt_max_extra_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="last_milestone_reached",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Höchster Tilgungs-Meilenstein (25/50/75/100), der bereits als erreicht gemeldet wurde — verhindert, dass dieselbe Meldung beim nächsten Dashboard-Aufruf erneut erscheint. Wird automatisch von check_new_milestones() gepflegt.",
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
