# Generated by Django 6.1.1 on 2026-09-03 17:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('checking', 'Girokonto'), ('savings', 'Sparkonto'), ('cash', 'Bargeld'), ('credit', 'Kreditkarte')], default='checking', max_length=20)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('starting_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('fixed', 'Fixkosten'), ('variable', 'Variable Kosten'), ('income', 'Einnahmen'), ('debt', 'Schuldentilgung'), ('savings', 'Sparen')], default='variable', max_length=20)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('keywords', models.CharField(blank=True, help_text="Komma-getrennte Stichworte für die automatische Zuordnung beim CAMT.053-Import (z.B. 'migros, coop, denner')", max_length=300)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('icon', models.CharField(default='💰', max_length=10)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Negativ = Ausgabe, positiv = Einnahme', max_digits=12)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('counterparty', models.CharField(blank=True, max_length=255)),
                ('import_ref', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.category')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
