# Generated by Django 6.1.1 on 2026-09-03 18:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_category_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("counterparty", models.CharField(blank=True, max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Negativ = Ausgabe, positiv = Einnahme",
                        max_digits=12,
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Tag im Monat, an dem die Buchung generiert wird (1–28, damit jeder Monat den Tag hat)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(28),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_transactions",
                        to="core.account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_transactions",
                        to="core.category",
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_month", "description"],
            },
        ),
    ]
