# Generated by Django 6.1.1 on 2026-09-04 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_recurringtransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month_start_day",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Tag im Monat, an dem der Budget-Monat beginnt (1 = Kalendermonat).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(28),
                        ],
                    ),
                ),
            ],
        ),
    ]
