# Generated by Django 6.1.1 on 2026-09-04 12:21

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_budgetsettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recurringtransaction",
            options={"ordering": ["description"]},
        ),
        migrations.AddField(
            model_name="category",
            name="target_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sparziel — optionaler Zielbetrag, z.B. für einen Sparumschlag.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="target_date",
            field=models.DateField(
                blank=True,
                help_text="Optionales Zieldatum, bis wann das Sparziel erreicht sein soll.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recurringtransaction",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("weekly", "Wöchentlich"),
                    ("biweekly", "Alle 2 Wochen"),
                    ("monthly", "Monatlich"),
                    ("yearly", "Jährlich"),
                ],
                default="monthly",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="recurringtransaction",
            name="month_of_year",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Für jährlich: Monat im Jahr.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AddField(
            model_name="recurringtransaction",
            name="start_date",
            field=models.DateField(
                default=datetime.date.today,
                help_text="Für alle 2 Wochen: Ankerdatum, ab dem der 2-Wochen-Rhythmus gezählt wird.",
            ),
        ),
        migrations.AddField(
            model_name="recurringtransaction",
            name="weekday",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Für wöchentlich/alle 2 Wochen: Wochentag (0=Montag ... 6=Sonntag).",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transfer_pair",
            field=models.OneToOneField(
                blank=True,
                help_text="Verknüpfte Gegenbuchung, falls dies ein Konto-zu-Konto-Transfer ist.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="recurringtransaction",
            name="day_of_month",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Für monatlich/jährlich: Tag im Monat (1–28, damit jeder Monat den Tag hat).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(28),
                ],
            ),
        ),
        migrations.CreateModel(
            name="CategoryBudgetHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "monthly_budget",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_history",
                        to="core.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Category budget history",
                "ordering": ["year", "month"],
                "unique_together": {("category", "year", "month")},
            },
        ),
    ]
