# Generated by Django 6.1.1 on 2026-09-04 12:49

from django.db import migrations, models

# Fest verdrahtete Kopie von Category.KIND_ICON_DEFAULTS zum Zeitpunkt dieser Migration —
# Migrationen dürfen nicht vom aktuellen Modellstand abhängen, der sich später ändern kann.
KIND_ICON_DEFAULTS = {
    "fixed": "\U0001F4C4",
    "variable": "\U0001F6D2",
    "income": "\U0001F4B5",
    "debt": "\U0001F4B3",
    "savings": "\U0001F437",
}
OLD_DEFAULT_ICON = "\U0001F4B0"


def backfill_icons_by_kind(apps, schema_editor):
    """Umschläge, die noch das frühere pauschale Standard-Icon tragen (vor Einführung
    des Icon-Katalogs war das Feld im Frontend nie editierbar), auf ein zur jeweiligen
    Art passendes Icon umstellen."""
    Category = apps.get_model("core", "Category")
    for kind, icon in KIND_ICON_DEFAULTS.items():
        Category.objects.filter(kind=kind, icon=OLD_DEFAULT_ICON).update(icon=icon)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_budget_history_transfers_targets_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Emoji aus dem Icon-Katalog im Frontend — bei leerem Wert wird beim Speichern ein zur Art passendes Icon gesetzt.",
                max_length=10,
            ),
        ),
        migrations.RunPython(backfill_icons_by_kind, noop),
    ]
