# Generated by Django 6.1.1 on 2026-09-04 12:59

from django.db import migrations, models

# Fest verdrahtete Kopie von Category.KIND_ICON_DEFAULTS zum Zeitpunkt dieser Migration.
# Icons waren vorher Emoji (siehe Migration 0006) — die lassen sich nicht sinnvoll auf
# Phosphor-Icon-Namen abbilden, daher werden ALLE bestehenden Umschläge auf das zu ihrer
# Art passende Phosphor-Icon zurückgesetzt, statt nur den alten Pauschal-Wert zu ersetzen.
KIND_ICON_DEFAULTS = {
    "fixed": "FileText",
    "variable": "ShoppingCart",
    "income": "TrendUp",
    "debt": "CreditCard",
    "savings": "PiggyBank",
}


def reset_icons_to_phosphor_defaults(apps, schema_editor):
    Category = apps.get_model("core", "Category")
    for kind, icon in KIND_ICON_DEFAULTS.items():
        Category.objects.filter(kind=kind).update(icon=icon)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_category_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Phosphor-Icon-Name aus dem Frontend-Katalog — bei leerem Wert wird beim Speichern ein zur Art passendes Icon gesetzt.",
                max_length=32,
            ),
        ),
        migrations.RunPython(reset_icons_to_phosphor_defaults, noop),
    ]
