# Generated by Django 6.1.1 on 2026-09-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_emergency_fund",
            field=models.BooleanField(
                default=False,
                help_text="Notfallfonds-Umschlag: bevor der Tilgungsplan-Rechner und der Sweep-Vorschlag Extra-Budget auf Schulden verteilen, wird zuerst die Lücke zum Sparziel (target_amount) dieses Umschlags gefüllt — bewährtes Prinzip aus der Schuldenberatung, damit die nächste unerwartete Rechnung nicht wieder auf der Kreditkarte landet. Es kann immer nur ein Umschlag als Notfallfonds markiert sein.",
            ),
        ),
    ]
