import {
  Airplane,
  Baby,
  Bank,
  Barbell,
  Basket,
  Books,
  Broom,
  Bus,
  Bicycle,
  Car,
  Coffee,
  Coins,
  Confetti,
  Couch,
  CreditCard,
  Drop,
  FileText,
  FilmSlate,
  FirstAidKit,
  Fire,
  ForkKnife,
  GameController,
  GasPump,
  Gift,
  HandCoins,
  Heartbeat,
  House,
  Lightbulb,
  PawPrint,
  Pill,
  PiggyBank,
  Receipt,
  Scissors,
  ShoppingCart,
  Star,
  Tag,
  Tooth,
  Train,
  TrendUp,
  TShirt,
  Wallet,
  WashingMachine,
  WifiHigh,
  Wrench,
  type Icon,
} from '@phosphor-icons/react'

// Zentrale Icon-Registry — die App verwendet durchgehend Phosphor-Icons (kein
// Emoji-Chrome), daher speichert Category.icon einen dieser Exportnamen statt
// eines Zeichens. Muss mit Category.KIND_ICON_DEFAULTS (core/models.py) im
// Einklang bleiben, was die dortigen Fallback-Werte betrifft.
export const ICON_COMPONENTS: Record<string, Icon> = {
  Wallet,
  CreditCard,
  Bank,
  TrendUp,
  Coins,
  Receipt,
  PiggyBank,
  HandCoins,
  ShoppingCart,
  Basket,
  ForkKnife,
  Coffee,
  Broom,
  WashingMachine,
  House,
  Couch,
  Lightbulb,
  Fire,
  Drop,
  WifiHigh,
  Wrench,
  Car,
  GasPump,
  Bus,
  Bicycle,
  Train,
  Airplane,
  Pill,
  FirstAidKit,
  Tooth,
  Barbell,
  Heartbeat,
  GameController,
  FilmSlate,
  Books,
  Confetti,
  Baby,
  PawPrint,
  Gift,
  FileText,
  Tag,
  Scissors,
  TShirt,
  Star,
}

export const ICON_CATALOG: { label: string; icons: string[] }[] = [
  { label: 'Finanzen', icons: ['Wallet', 'CreditCard', 'Bank', 'TrendUp', 'Coins', 'Receipt', 'PiggyBank', 'HandCoins'] },
  { label: 'Essen & Haushalt', icons: ['ShoppingCart', 'Basket', 'ForkKnife', 'Coffee', 'Broom', 'WashingMachine'] },
  { label: 'Wohnen', icons: ['House', 'Couch', 'Lightbulb', 'Fire', 'Drop', 'WifiHigh', 'Wrench'] },
  { label: 'Verkehr', icons: ['Car', 'GasPump', 'Bus', 'Bicycle', 'Train', 'Airplane'] },
  { label: 'Gesundheit', icons: ['Pill', 'FirstAidKit', 'Tooth', 'Barbell', 'Heartbeat'] },
  { label: 'Freizeit & Familie', icons: ['GameController', 'FilmSlate', 'Books', 'Confetti', 'Baby', 'PawPrint', 'Gift'] },
  { label: 'Sonstiges', icons: ['FileText', 'Tag', 'Scissors', 'TShirt', 'Star'] },
]
