# Generated by Django 6.1.1 on 2026-09-04 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_recurringtransaction"),
        ("imports_camt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optionaler Name zur Übersicht",
                        max_length=150,
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("description", "Beschreibung"),
                            ("counterparty", "Gegenpartei"),
                            ("either", "Beschreibung oder Gegenpartei"),
                        ],
                        default="either",
                        max_length=20,
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("contains", "enthält"),
                            ("startswith", "beginnt mit"),
                            ("exact", "ist genau"),
                        ],
                        default="contains",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Text, nach dem gesucht wird (Gross-/Kleinschreibung egal)",
                        max_length=200,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0, help_text="Höhere Zahl wird zuerst geprüft"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_rules",
                        to="core.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "id"],
            },
        ),
    ]
