# Generated by Django 6.1.1 on 2026-09-04 10:03, hand-edited: reordered so the
# new columns exist and are backfilled from the old ones before those are
# dropped (autodetector originally put RemoveField first).

from django.db import migrations, models


def backfill_conditions(apps, schema_editor):
    Rule = apps.get_model("imports_camt", "Rule")
    for rule in Rule.objects.all():
        # Alte Regeln kannten nur ein Feld ("description"/"counterparty"/"either")
        # mit einem Wert — "either" wird als Beschreibungs-Bedingung übernommen,
        # da die neue UND-Verknüpfung kein direktes Äquivalent zu "oder" hat.
        if rule.field == "counterparty":
            rule.counterparty_value = rule.value
            rule.counterparty_match_type = rule.match_type
        else:
            rule.description_value = rule.value
            rule.description_match_type = rule.match_type
        rule.save(update_fields=["description_value", "description_match_type", "counterparty_value", "counterparty_match_type"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("imports_camt", "0002_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="amount_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Leer lassen für keine Obergrenze",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="amount_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Leer lassen für keine Untergrenze",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="counterparty_match_type",
            field=models.CharField(
                choices=[
                    ("contains", "enthält"),
                    ("startswith", "beginnt mit"),
                    ("exact", "ist genau"),
                ],
                default="contains",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="counterparty_value",
            field=models.CharField(
                blank=True,
                help_text="Leer lassen, um Gegenpartei nicht zu prüfen",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="description_match_type",
            field=models.CharField(
                choices=[
                    ("contains", "enthält"),
                    ("startswith", "beginnt mit"),
                    ("exact", "ist genau"),
                ],
                default="contains",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="description_value",
            field=models.CharField(
                blank=True,
                help_text="Leer lassen, um Beschreibung nicht zu prüfen",
                max_length=200,
            ),
        ),
        migrations.RunPython(backfill_conditions, noop_reverse),
        migrations.RemoveField(
            model_name="rule",
            name="field",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="match_type",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="value",
        ),
    ]
